### ISSUE TITLE
feature: storage service dropdown copy telnet, curl command

### ISSUE THREAD

**Issue by bodik** [snerstack/sner-monorepo#1]
add storage service dropdown copy telnet, curl command

**Comment by Filiq** [comment]
@bodik please review the feature: https://github.com/snerstack/sner-monorepo/compare/main...feature/copy-telnet-curl-cmd

**Comment by bodik** [comment]
* refactored initiali implementation and merged into current workbranch
@Filiq 
* [ ] drop the feature branch

**Comment by Filiq** [comment]
branch dropped
