### ISSUE TITLE
ux: match blue color value in css with pre-frontend version

### ISSUE THREAD

**Issue by bodik** [snerstack/sner-monorepo#14]
ux: match blue color value in css with pre-frontend version

**Comment by bodik** [comment]
FYI https://github.com/snerstack/sner-monorepo/blob/main/server/sner/server/static/bootstrap/css/themed-_variables.scss

**Comment by Filiq** [comment]
resolved

https://github.com/snerstack/sner-monorepo/commit/5c243a1560be5a1df448ccdfdc10ebef229e2ffa
