### ISSUE TITLE
frontend/server: visuals portinfos nocrop error 500 on backend

### ISSUE THREAD

**Issue by bodik** [snerstack/sner-monorepo#19]
frontend/server: visuals portinfos nocrop error 500 on backend

ui: error while fetching data
server: `ValueError: invalid literal for int() with base 10: 'no crop'`

**Comment by bodik** [comment]
graph not being rerendered on change of parameters

**Comment by Filiq** [comment]
graphs are now rerendered after changing the parameters

https://github.com/snerstack/sner-monorepo/commit/381475c819bebf5137fdd8f974d03a586da5f0d6
