### ISSUE TITLE
experiment: test semgrep

### ISSUE THREAD

**Issue by bodik** [snerstack/sner-monorepo#21]
experiment: test semgrep

**Comment by Filiq** [comment]
@bodik please check https://github.com/snerstack/sner-monorepo/commit/da3595ab369a125e7d700cb4dea3276f26508932 and https://github.com/snerstack/sner-monorepo/commit/db0069b69ae766e0e01571d1aedc540356acbe69

**Comment by bodik** [comment]
I've not used proposed solution, but implemented simpler yet not-so-powerful approach utilizing only OSS scanner
