### ISSUE TITLE
selenium: avoid implicit wait/sleep if possible

### ISSUE THREAD

**Issue by bodik** [snerstack/sner-monorepo#23]
selenium: avoid implicit wait/sleep if possible

https://github.com/snerstack/sner-monorepo/blob/da65e73d3dc0d5b66288bd326a69e4f9452db113/server/tests/selenium/__init__.py#L51

are there any alternatives to sleep here ?

**Comment by Filiq** [comment]
resolved, replaced with selenium wait logic

https://github.com/snerstack/sner-monorepo/commit/2b222f5caa4e658427829c8f29230d9aad438631
