### ISSUE TITLE
ux: configurable tag colors

### ISSUE THREAD

**Issue by bodik** [snerstack/sner-monorepo#24]
ux: configurable tag colors
* static - color
* prefix - color

**Comment by Filiq** [comment]
solved, see https://github.com/snerstack/sner-monorepo/commit/5db623a6dcec5f3c51c887bf6ba46dc09b01f681, https://github.com/snerstack/sner-monorepo/commit/c7537d559fb9947bd85894b8c67d09e16c9710da

**Comment by bodik** [comment]
* refactored in review1 branch
* [ ] @Filiq drop origin/devel-tag-colors branch
