### ISSUE TITLE
ux: proper quickjump

### ISSUE THREAD

**Issue by bodik** [snerstack/sner-monorepo#25]
* original implementation of quickjump is not really good
https://github.com/snerstack/sner-monorepo/blob/main/server/sner/server/storage/views/quickjump.py#L22

* fix, jump on click on dropdown
* change, jump on port require ? `p:` prefix ? or any other nice way to jump on servicelist with port filtered

**Comment by Filiq** [comment]
solved, see https://github.com/snerstack/sner-monorepo/commit/d9e3e0524be70ff1d01df206d9bea3da8e02252b, https://github.com/snerstack/sner-monorepo/commit/cedfafbe55102800469f278d127d7d3eb67e63aa

**Comment by bodik** [comment]
* merged to review branch
* [ ] @Filiq cleanup origin/devel-quickjump branch

**Comment by Filiq** [comment]
origin/devel-quickjump dropped
