### ISSUE TITLE
ci: chain jobs

### ISSUE THREAD

**Issue by bodik** [snerstack/sner-monorepo#58]
* run selenium and semgrep only if frontend and backend tests finish successfully ?
* is it possible to share assets to save resources (simple or ignore) ?
* experiment and show-case in separate repo

**Comment by bodik** [comment]
experiment in separate repo

**Comment by bodik** [comment]
or just branch from devel-bodik-review1-integrations (but its heavy forcepushed devel branch now)

**Comment by bodik** [comment]
check and use 

https://github.com/snerstack/sner-ci-chained-jobs/actions/runs/8946118535

**Comment by bodik** [comment]
* [ ] picked up from https://github.com/snerstack/sner-ci-chained-jobs/actions/runs/8946118535, merged in current workbranch

@filiq
* [ ] delete extra repo
* [ ] close this issue

**Comment by Filiq** [comment]
extra repo deleted
