### ISSUE TITLE
doc: cannot make dev environment

### ISSUE THREAD

**Issue by bodik** [snerstack/sner-monorepo#7]
```
user@sner-frontdev:/opt/sner# make dev
/bin/sh: 2: npm: not found
make: *** [Makefile:4: dev] Error 127
```

**Comment by Filiq** [comment]
resolved, added nodejs and npm packages to the installation guide

https://github.com/snerstack/sner-monorepo/blob/8265803c49060e183f19afd2e025583d76feaa0c/README.md?plain=1#L8
